ENTRY(_start)

SECTIONS
{
    /* Kernel diletakkan mulai dari alamat 1MB */
    . = 1M;

    .text BLOCK(4K) : ALIGN(4K)
    {
        *(.multiboot)
        *(.text)
    }

    .rodata BLOCK(4K) : ALIGN(4K)
    {
        *(.rodata)
    }

    .data BLOCK(4K) : ALIGN(4K)
    {
        *(.data)
    }

    .bss BLOCK(4K) : ALIGN(4K)
    {
        *(COMMON)
        *(.bss)
    }

    /* TEPAT DI SINI: Definisikan simbol akhir kernel */
    end = .;
}